### PR TITLE
mpu6050: add devfs api and user space application

### PR DESCRIPTION
**Pull request by joy4eg**
Summary:
- Split driver into several parts (main, sysfs, devfs)
- Add sysfs compatibility class (in /sys/class/mpu6050)
- Rename _mpu6050-regs.h_ into _mpu6050_regs.h_ to support one name convention style
- Add devfs driver part:
  - Create one major (42) device with two minor numbers (0 - stream, 1 - buffered)
  - Save up to 16 measurements in 'buffered' device (FIFO)
  - Add locking protection for 'stream' device (it can only be read from single application)
  - Save measurements from 'stream' device to 'buffered' only one per second.
- Add user space application that can read the data from two devices in the same time

### CODE REVIEW

**Review by an1kh — CHANGES_REQUESTED** [review]
PR looks almost perfect, but has a build error:
```
/home/andriy/ldd_training2/gl-kernel-training/mpu6050/mpu6050_devfs.c: In function ‘mpu6050_devfs_data_can_save’:
/home/andriy/ldd_training2/gl-kernel-training/mpu6050/mpu6050_devfs.c:79:28: error: invalid operands to binary > (have ‘ktime_t {aka union ktime}’ and ‘int’)
  if (ctx->last_access_time > 0) {
                            ^
```

BTW ```#pragma once``` guard looks unused in kernel but checkpatch doesn't warn about it.

**Comment by an1kh** [comment]
Also suggest to use more explaining commit messages (of cause not to file renames).

**Comment by joy4eg** [comment]
@an1kh Thanks, I will fix this.

BTW: what gcc version do you have ?
I successfully tested this PR with gcc 7.1 (ARM linaro) and gcc 7.2. (x86, red hat)

**Comment by an1kh** [comment]
```
gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4) 
```

After the fix:
```
/home/andriy/ldd_training2/gl-kernel-training/mpu6050/mpu6050_devfs.c: In function ‘mpu6050_devfs_data_can_save’:
/home/andriy/ldd_training2/gl-kernel-training/mpu6050/mpu6050_devfs.c:78:28: error: invalid initializer
  const ktime_t time_zero = 0;
                            ^
```

**Comment by an1kh** [comment]
And one more thing: providing the patch to show the fix is OK. But while changes are not yet merged, it is better to update the commit that added those lines.

**Comment by an1kh** [comment]
This patch solved the compilation error for me, but I didn't tested it:
```
-       if (ctx->last_access_time > 0) {
+       if (ctx->last_access_time.tv64 > 0) {
```

**Comment by joy4eg** [comment]
I finally found the main issue: https://github.com/torvalds/linux/commit/2456e855354415bfaeb7badaa14e11b3e02c8466
My kernel version is 4.13.10, upstream commit was added in v4.10-rc1. I guess your kernel version is older ...

**Comment by joy4eg** [comment]
Now it can be successfully built using old/new kernels.

**Review by an1kh — APPROVED** [review]
Now it is OK. Well done!

**Pull request merged**
