### PR TITLE
Practic 1: Mpu_6050 fixup part1

### PR DESCRIPTION
**Pull request by dmytrokirtoka**
- fixed tree name
- i2c client get once for read session
- fixed set/remove i2c_client by install/remove driver
- fixed typo in temperature show func name
- modified SYSFS declaration for class files
- procfs not implemented by now

Signed-off-by: dmytro.kirtoka dimk334@gmail.com

### CODE REVIEW

**Review by AleksandrBulyshchenko — COMMENTED** [review]
I'd like to encourage you to follow [recommendation in wiki](https://github.com/Kernel-GL-HRK/gl-kernel-training-2017/wiki/Pull-Request-Guideline).

224061b0 ("Lesson 7 mpu6050 module") requires splitting into parts.

Try to create more atomic commits.
- Avoid mixing bugfixes and functional changes.
- For bugfixes - provide bugs description in commit message.

**Comment by an1kh** [comment]
Want to add to comment above: do not include unneeded code (e.g. commented out and unused defines because of that comment).

But resulting code looks good, all issues are fixed. Well done!

**Comment by AleksandrBulyshchenko** [comment]
@dmytrokirtoka,
Does this PR relevant any more?
Please comment and either update or close.

**Comment by dmytrokirtoka** [comment]
No more relevant.

**Pull request closed without merging**
